# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('observation', models.TextField(null=True)),
                ('construction', models.TextField(null=True)),
                ('limites_precautions', models.TextField(null=True)),
                ('fiabilite', models.TextField(null=True)),
                ('amelioration', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupementVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ValeurVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=255)),
                ('depuis_version', models.CharField(max_length=20)),
                ('jusque_version', models.CharField(max_length=20, null=True)),
                ('detail', models.TextField(null=True)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docdv3f.DescriptionVariable')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('nom', models.CharField(max_length=255)),
                ('code_modele', models.CharField(max_length=3)),
                ('table_associee', models.CharField(max_length=50)),
                ('depuis_version', models.CharField(max_length=20)),
                ('jusque_version', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=255)),
                ('contrainte', models.CharField(max_length=3, null=True)),
                ('code_etape_pour_creation', models.IntegerField()),
                ('table_pour_creation', models.CharField(max_length=50, null=True)),
                ('description_simplifiee', models.TextField(null=True)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docdv3f.DescriptionVariable')),
            ],
        ),
        migrations.AddField(
            model_name='groupementvariable',
            name='variables_associees',
            field=models.ManyToManyField(to='docdv3f.Variable'),
        ),
    ]
