# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docdv3f', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='code_etape_pour_creation',
        ),
    ]
