# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdv3f', '0002_remove_variable_code_etape_pour_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='code_modele',
            field=models.IntegerField(),
        ),
    ]
