# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdv3f', '0003_auto_20160314_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionvariable',
            name='amelioration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionvariable',
            name='construction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionvariable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionvariable',
            name='fiabilite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionvariable',
            name='limites_precautions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionvariable',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valeurvariable',
            name='jusque_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='contrainte',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='description_simplifiee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='jusque_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='table_pour_creation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
