# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationBDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_config', models.CharField(max_length=100, unique=True)),
                ('hote', models.CharField(max_length=255)),
                ('bdd', models.CharField(max_length=255)),
                ('utilisateur', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
                ('type_bdd', models.CharField(choices=[('DVF+', 'Base de type DVF+'), ('DV3F', 'Base de type DV3F')], max_length=4)),
                ('active', models.BooleanField()),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
