# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('code_actualite', models.CharField(max_length=2, null=True)),
                ('commune_absorbante', models.CharField(max_length=5, null=True)),
                ('commune_emancipee', models.CharField(max_length=5, null=True)),
                ('date_absorbtion', models.DateField(null=True)),
                ('date_separation', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicateur.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_indic', models.CharField(max_length=100)),                
                ('periode', models.CharField(choices=[('a', 'annuel'), ('ma', 'multi-annuel')], max_length=2)),
                ('variable', models.CharField(max_length=50)),
                ('annee_debut', models.IntegerField(null=True)),
                ('annee_fin', models.IntegerField(null=True)),
                ('code_typo', models.CharField(max_length=5)),
                ('type_graphe', models.CharField(choices=[('bar', 'diagramme à barre'), ('line-dotted', 'diagramme point-ligne')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('communes', models.ManyToManyField(to='indicateur.Commune')),
                ('departements', models.ManyToManyField(to='indicateur.Departement')),
                ('epcis', models.ManyToManyField(to='indicateur.Epci')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicateur.Departement'),
        ),
        migrations.AddField(
            model_name='commune',
            name='epci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicateur.Epci'),
        ),
    ]
