# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_indic', models.CharField(choices=[('somme', 'Somme'), ('compte', 'Décompte'), ('mediane_10', 'Médiane')], max_length=30)),
                ('unite', models.CharField(max_length=30, null=True)),
                ('periode', models.CharField(choices=[('a', 'annuel'), ('ma', 'multi-annuel')], max_length=2)),
                ('variable', models.CharField(max_length=50)),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('code_typo', models.CharField(choices=[('999', 'Tout type de mutation'), ('8', 'Adjudication'), ('9', 'Expropriation'), ('7', 'Echange'), ('4', 'Volume'), ('31', 'Vefa - Industriel et Commercial'), ('32', 'Vefa - Appart'), ('33', 'Vefa - Maison'), ('34', 'Vefa - Non déterminé'), ('211', 'Non Bati - Terrain naturels'), ('212', 'Non Bati - Terrains forestiers'), ('213', 'Non Bati - Terrains agricoles'), ('221', 'Non Bati - Terrains artificialisés'), ('241', 'Non Bati - Terrains non déterminés'), ('231', 'Non Bati - Terrains mixtes'), ('25', 'Non Bati - Terrain à bâtir'), ('111', 'Bati - Logement/industriel et commercial'), ('112', 'Bati - Industriel et Commercial'), ('121', 'Bati - Appartements'), ('122', 'Bati - Appartement'), ('131', 'Bati - Maisons'), ('132', 'Bati - Maison'), ('141', 'Bati - Bien agricole'), ('142', 'Bati - Dépendance Logement'), ('143', 'Bati - Logement mixte'), ('144', 'Bati - Non déterminé'), ('145', 'Bati - Bien forestier')], max_length=5)),
                ('type_graphe', models.CharField(choices=[('bar', 'diagramme à barre'), ('line-dotted', 'diagramme point-ligne')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatIndicateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_territoire', models.IntegerField()),
                ('type_territoire', models.CharField(max_length=50)),
                ('id_indicateur', models.IntegerField()),
                ('annee', models.IntegerField(null=True)),
                ('resultat', models.IntegerField()),
            ],
        ),
    ]
