# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='unite',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
