# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0002_auto_20160203_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='code_actualite',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='commune_absorbante',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='commune_emancipee',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='date_absorbtion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='date_separation',
            field=models.DateField(null=True),
        ),
    ]
