# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0003_auto_20160310_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicateur',
            name='annee_debut',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='annee_fin',
            field=models.IntegerField(default=2013),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='type_indic',
            field=models.CharField(choices=[('somme', 'Somme'), ('compte', 'Décompte'), ('mediane_10', 'Médiane')], max_length=30),
        ),
    ]
