# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0003_auto_20160205_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
