# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0006_auto_20160209_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateur',
            name='nom',
            field=models.CharField(default='Nom Indicateur', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicateur',
            name='type_graphe',
            field=models.CharField(choices=[('bar', 'diagramme à barre'), ('line-dotted', 'diagramme point-ligne')], default='bar', max_length=20),
            preserve_default=False,
        ),
    ]
