# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0004_auto_20160311_1542'),
        ('indicateur', '0007_auto_20160211_2131'),
    ]

    operations = [
    ]
