# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicateur', '0008_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatIndicateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_territoire', models.IntegerField()),
                ('type_territoire', models.CharField(max_length=50)),
                ('id_indicateur', models.IntegerField()),
                ('annee', models.IntegerField(null=True)),
                ('resultat', models.IntegerField()),
            ],
        ),
    ]
